/**
 * The browser-side funnel events, pushed to Google Tag Manager's dataLayer.
 *
 * Kept in its own module, reading NO configuration, so client components can
 * fire events without importing `lib/tracking-config.ts` (which reads the
 * Conversions API token). The isolation test enforces that boundary.
 *
 * Two hard rules for every event here, both tested in
 * `lib/__tests__/data-layer.test.ts`:
 *
 * ⛔ NO PII. No phone, email, name, address, message text or payout detail
 *    ever enters the dataLayer. Tag Manager forwards the dataLayer to Google
 *    and Meta, and a seller's phone number in a GA4 event parameter is a
 *    policy violation that cannot be deleted afterwards. The type below makes
 *    it impossible to write one by accident, and `pushEvent` drops any key or
 *    value that looks like contact data anyway, in case the types are bypassed.
 *
 * ⛔ NO HEALTH TERMS in anything Meta receives. Meta restricts health-related
 *    data. Event names are neutral (`lead_submit`, never a product word). The
 *    three events a Meta pixel tag fires on (`lead_submit`, `bulk_lead_submit`,
 *    `mail_kit_request`) carry no product information at all. `product_category`
 *    appears only on GA4-only soft events, and docs/tracking-setup.md says the
 *    Meta tags forward `event_id` and nothing else.
 *
 * The money events carry `event_id`, generated by the SERVER and returned in
 * the API response. The server sends the same id to the Conversions API, so
 * Meta collapses the browser and server halves into one lead.
 */

/** Normalized product categories. GA4-only: never forward these to Meta. */
export type ProductCategory = 'test_strips' | 'cgm' | 'infusion_sets' | 'lancets' | 'other'

export type LeadType = 'sell' | 'bulk' | 'mail_kit'
export type ContactMethod = 'call' | 'text' | 'email' | 'website'
export type ContactTarget = 'house' | 'buyer'

export type TrackingEvent =
  // /sell wizard
  | { event: 'sell_start' }
  | { event: 'sell_product_selected'; product_category: ProductCategory; item_number: number }
  | { event: 'sell_phone_captured' }
  | { event: 'sell_buyers_shown'; buyer_count: number; mail_in_offered: boolean; state: string }
  | { event: 'lead_submit'; event_id: string; lead_type: 'sell'; channel: 'sms' | 'email'; item_count: number }
  // /mail-in-kit
  | { event: 'mail_kit_start' }
  | { event: 'mail_kit_step'; step: 2 | 3 }
  | { event: 'mail_kit_request'; event_id: string; lead_type: 'mail_kit'; item_count: number }
  // /sell-test-strips-in-bulk
  | { event: 'bulk_form_start' }
  | { event: 'bulk_lead_submit'; event_id: string; lead_type: 'bulk' }
  // everywhere
  | { event: 'contact_click'; method: ContactMethod; target: ContactTarget }
  | { event: 'sign_up'; role: 'customer' | 'buyer' }

export type TrackingEventName = TrackingEvent['event']

/** The events a Meta pixel tag fires on. They must carry no product data. */
export const META_EVENTS = ['lead_submit', 'bulk_lead_submit', 'mail_kit_request'] as const

/** Keys that would carry contact data. Dropped on sight. */
const PII_KEY = /phone|email|e_mail|name|address|street|city|zip|postal|handle|payout|message|note|details|user_data|ssn|dob|birth/i
/** Values that look like an email address or a phone number. Dropped on sight. */
const EMAIL_VALUE = /[^\s@]+@[^\s@]+\.[^\s@]+/
const PHONE_VALUE = /(?:\d[\s().-]*){7,}/

/**
 * Removes anything that looks like contact data from an event payload, and any
 * nested object (the shape Google's `user_data` would take). Pure, exported for
 * the test. `event_id` is exempt from the phone-shaped check only: a UUID such
 * as `…-4000-8000-000000000001` has long hyphenated digit runs.
 */
export function stripPii(payload: Record<string, unknown>): Record<string, unknown> {
  const clean: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(payload)) {
    if (PII_KEY.test(key)) continue
    if (typeof value === 'string' && (EMAIL_VALUE.test(value) || (key !== 'event_id' && PHONE_VALUE.test(value)))) continue
    if (value !== null && typeof value === 'object') continue
    clean[key] = value
  }
  return clean
}

type DataLayerWindow = { dataLayer?: Record<string, unknown>[] }

export function pushEvent(e: TrackingEvent): void {
  if (typeof window === 'undefined') return
  const w = window as unknown as DataLayerWindow
  // Tag Manager creates the dataLayer. When it is not loaded (no container
  // configured, an excluded page, or the visitor opted out) events go nowhere.
  if (!w.dataLayer) return
  const { event, ...payload } = e
  w.dataLayer.push({ event, ...stripPii(payload) })
}

/** Maps the catalog's display category to the neutral code the events use. */
export function productCategoryCode(category: string | undefined | null): ProductCategory {
  switch (category) {
    case 'Test Strips':
      return 'test_strips'
    case 'CGM':
      return 'cgm'
    case 'Infusion Sets':
      return 'infusion_sets'
    case 'Lancets':
      return 'lancets'
    default:
      return 'other'
  }
}
